enum GErrorCode 
{
	Success = 0,
	MessageFormatError = 1000,
	MessageSeqOmmitError = 1001,
	InvalidUserError = 2000,
	InvalidAccessTokenError = 2001,
	DuplicateConnectionError = 3000,
	ReconnectTimeoutError = 4000,
	ResponseTimeoutError = 4001,
	AlreadyLoginSessionError = 5000,
	CanNotCreateCastGroup = 5001
};

struct GUserData 
{
	string UserID;
	uint32 UserSEQ;
	uint32 Frame;
};

message MsgCliSvr_Login_Req : 1
{
	string	UserID;
};

message MsgSvrCli_Login_Ans : 1
{
	GErrorCode	ErrorCode;
	GUserData	UserData;
};

message MsgCliSvr_UpdateFrame_Req : 2
{
};

message MsgSvrCli_UpdateFrame_Ans : 2
{
	GErrorCode	ErrorCode;
	uint32 Frame;
};

message MsgCliSvr_JoinChannel_Req : 00010001
{
};

message MsgSvrCli_JoinChannel_Ans : 00010001
{
	GErrorCode ErrorCode;
	uint32 ChannelSEQ;
	list<GUserData> UserDatas;
};

message MsgSvrCli_JoinChannel_Ntf : 10010001
{
	uint32 UserCount;
	GUserData NewUserData;
};

message MsgCliSvr_SendMessage_Ntf : 1020
{
	string Message;
};

message MsgSvrCli_SendMessage_Ntf : 1020
{
	string UserID;
	string Message;
};

message MsgSvrSvr_SendMessage_Ntf : 1022
{
	string UserID;
	string Message;
};

message MsgCliSvr_LeaveChannel_Req : 00010003
{
};

message MsgSvrCli_LeaveChannel_Ans : 00010003
{
	GErrorCode ErrorCode;
};

message MsgSvrCli_LeaveChannel_Ntf : 10010003
{
	GUserData LeaveUserData;
};

message MsgSvrCli_Kickout_Ntf : 10000003
{
	GErrorCode	ErrorCode;
};

message MsgCliSvr_HeartBeat_Ntf : 10000004
{
	int32 msg_seq;
};

message MsgSvrCli_HeartBeat_Ntf : 10000004
{
	int32 msg_seq;
};
