.cpp %%
#include "MessageCommon.h"
namespace Message { namespace Item {
%%

.cs %%
namespace Message { namespace Item {
%%

message MsgCliSvr_OpenPackage_Req : 130000001
{
	uint64 item_seq;
};

message MsgSvrCli_OpenPackage_Ans : 130000002
{
	ErrorCode error_code;
	ItemData item_data;
};

message MsgSvrCli_AddItem_Ntf : 130000003
{
	list<ItemData> item_datas;
};

message MsgSvrCli_UpdateItem_Ntf : 130000004
{
	list<ItemData> item_datas;
};

.cpp %%
}}
%%
.cs %%
}}
%%