.cpp %%
namespace Message { 
%%
.cs %%
namespace Message { 
%%

enum ErrorCode
{
	Success = 0,
	MessageFormatError = 1000,
	MessageSeqOmmitError = 1001,
	InvalidUserError = 2000,
	InvalidAccessTokenError = 2001,
	InvalidSeviceName = 2002,
	DuplicateConnectionError = 3000,
	ReconnectTimeoutError = 4000,
	ResponseTimeoutError = 4001,
	AlreadyLoginSessionError = 5000,
	CanNotCreateCastGroup = 5001,
	DuplicateNameError,
	CreateAccountError,
	InvalidItemID,
	InvalidItemIndex,
	InvalidItemSEQ,
	UndefineError = 99999,
};

enum AccountType
{
	Invalid,
	Dev = 1,
	Google = 2,
	Apple = 3,
	Facebook = 4
};

enum AccountState
{
	Invalid,
	Normal,
	Penalty,
	OnDelete,
	Deleted
};

enum CounterType
{
	Invalid = 0,
	Gold = 1,
	Cash = 2,
};

enum ItemType
{
	Invalid,
	Equip,
	Package,
};

enum EquipItemPartType
{
	Invalid,
	Cloak,
	Legs,
	Body,
	Boots,
	Beard,
	Head,
	Gloves,
	LeftHand,
	RightHand,
	Max
};

enum DungeonTileType
{
	Invalid,
	Floor,
	Wall,
	Door,
	StairDown,
	StairUp
};

struct MailData
{
	uint64 mail_seq;
	string mail_message;
	uint64 expire_date;
	uint32 item_index;
	uint32 item_count;
};

struct CounterData
{
	CounterType counter_type;
	uint64 update_date;
	int32 count;
};

struct ItemData
{
	uint64 item_seq;
	uint32 item_index;
	int32 item_count;
};

struct EquipItemData(ItemData)
{
	EquipItemPartType part_type;
};

struct UserData
{
	uint64 user_seq;
	string user_name;
};

struct Vector2Int
{
	int32 x;
	int32 y;
};

struct Monster
{
	uint64 seq;
	Vector2Int position;
};

.cpp %%
}
%%

.cs %%
}
%%