.cpp %%
#include "data.h"
%%

.cs %%
using data;
%%


message MsgCliSvr_Login_Req 	: 10000001
{
	string user_id;
};

message MsgSvrCli_Login_Ans 	: 10000001
{
	ErrorCode error_code;
	UserData user_data;
};

message MsgSvrCli_Kickout_Ntf 	: 10000003
{
	ErrorCode error_code;
};

message MsgCliSvr_HeartBeat_Ntf	: 10000004
{
	uint32 msg_seq;
};

message MsgSvrCli_HeartBeat_Ntf : 10000004
{
	uint32 msg_seq;
};
