.cpp%%
#include "MessageCommon.h"
namespace Message{ namespace Dungeon {
%%
.cs %%
namespace Message { namespace Dungeon {
%%

message MsgCliSvr_CreateDungeon_Req : 040000001
{
};

message MsgSvrCli_CreateDungeon_Ans : 040000001
{
	ErrorCode error_code;
	int32 width;
	int32 height;
	Vector2Int start;
	array<DungeonTileType> tiles;
};

.cpp %%
}}
%%
 .cs %%
}}
%%