.cpp %%
#include "MessageCommon.h"
namespace Handler { namespace User {
%%

.cs %%
namespace Handler { namespace User {
%%

message MsgCliSvr_Login_Req : 00011
{
	string account_id;
	AccountType account_type;
};

message MsgSvrCli_Login_Ans : 00012
{
	ErrorCode error_code;
	UserData user_data;
};

message MsgCliSvr_Create_Req : 00021
{
	string account_id;
	AccountType account_type;
	string user_name;
};

message MsgSvrCli_Create_Ans : 00022
{
	ErrorCode error_code;
};

message MsgSvrCli_Counter_Ntf : 00031
{
	list<CounterData> counter_datas;
};

message MsgCliSvr_Delete_Req : 32
{
};

message MsgSvrCli_Delete_Ans : 33
{
	ErrorCode error_code;
};

message MsgCliSvr_Restore_Req : 34
{
};

message MsgSvrCli_Restore_Ans : 35
{
	ErrorCode error_code;
};

.cpp %%
}}
%%

.cs %%
}}
%%