.cpp %%
#include "MessageCommon.h"
namespace Handler{ namespace Lobby {
%%

.cs %%
namespace Handler { namespace Lobby {
%%

message MsgCliSvr_Join_Req : 120000001
{
};

message MsgSvrCli_Join_Ans : 120000002
{
	ErrorCode error_code;
};

message MsgSvrCli_Mail_Ntf : 120000003
{
	list<MailData> mail_datas;
};

message MsgCliSvr_OpenMail_Req : 120000004
{
	uint64 mail_seq;
};

message MsgSvrCli_OpenMail_Ans : 120000005
{
	ErrorCode error_code;
};

.cpp %%
}}
%%

.cs %%
}}
%%