.cpp%%
#include "MessageCommon.h"
namespace Message{ namespace Dungeon {
%%
.cs %%
namespace Message { namespace Dungeon {
%%

message MsgCliSvr_CreateDungeon_Req : 040000001
{
};

message MsgSvrCli_CreateDungeon_Ans : 040000001
{
	ErrorCode error_code;

	int32 width;
	int32 height;
	array<DungeonTileType> tiles;

	uint64 unit_seq;
	Vector2Int position;

	list<Player> comrades;
	list<Monster> enemies;
};

message MsgCliSvr_PlayerMove_Ntf : 040000002
{
	Vector2Int destination;
};

message MsgSvrCli_UnitPosition_Ntf : 040000003
{
	uint64 unit_seq;
	Vector2Int position;
};

message MsgSvrCli_CreatePlayer_Ntf(Player) : 040000004
{
};

message MsgSvrCli_DestroyUnit_Ntf : 040000005
{
	uint64 unit_seq;
};

.cpp %%
}}
%%
 .cs %%
}}
%%