enum ErrorCode {
	Success = 0,
	MessageFormatError = 1000,
	MessageSeqOmmitError = 1001,
	InvalidUserError = 2000,
	InvalidAccessTokenError = 2001,
	DuplicateConnectionError = 3000,
	ReconnectTimeoutError = 4000,
	ResponseTimeoutError = 4001,
	AlreadyLoginSessionError = 5000,
	CanNotCreateCastGroup = 5001
};

struct UserData {
	string UserID;
	uint32 UserSEQ;
};

message MsgCliSvr_Login_Req : 10000001
{
	string	UserID;
};

message MsgSvrCli_Login_Ans : 10000001
{
	ErrorCode	ErrorCode;
	UserData	UserData;
};

message MsgCliSvr_JoinChannel_Req : 00010001
{
};

message MsgSvrCli_JoinChannel_Ans : 00010001
{
	ErrorCode ErrorCode;
};

message MsgSvrCli_JoinChannel_Ntf : 10010001
{
	string SessionKey;
	int32 SessionCount;
};

message MsgCliSvr_SendMessage_Ntf : 1020
{
	string Message;
};

message MsgSvrCli_SendMessage_Ntf : 1020
{
	string Message;
};

message MsgSvrSvr_SendMessage_Req : 0021
{
	string Message;
};

message MsgSvrSvr_SendMessage_Ans : 0022
{
	string Message;
};

message MsgSvrSvr_SendMessage_Ntf : 1022
{
	string Message;
};

message MsgCliSvr_LeaveChannel_Req : 00010003
{
};

message MsgSvrCli_LeaveChannel_Ans : 00010003
{
	ErrorCode error_code;
};

message MsgSvrCli_LeaveChannel_Ntf : 10010003
{
	string session_key;
};

message MsgSvrCli_Kickout_Ntf : 10000003
{
	ErrorCode	error_code;
};

message MsgCliSvr_HeartBeat_Ntf : 10000004
{
	int32 msg_seq;
};

message MsgSvrCli_HeartBeat_Ntf : 10000004
{
	int32 msg_seq;
};
