.cpp %%
#include "MessageCommon.h"
namespace Message { namespace Item {
%%

.cs %%
namespace Message { namespace Item {
%%

message MsgSvrCli_AddItem_Ntf		: 0x00002001
{
	list<ItemData> item_datas;
};

message MsgSvrCli_UpdateItem_Ntf	: 0x00002002
{
	list<ItemData> item_datas;
};

message MsgCliSvr_OpenPackage_Req	: 0x00002003
{
	int64 item_no;
};

message MsgSvrCli_OpenPackage_Ans	: 0x00002003
{
	ErrorCode error_code;
};

message MsgCliSvr_EquipItem_Req		: 0x00002004
{
	int64 item_no;
};

message MsgSvrCli_EquipItem_Ans		: 0x00002004
{
	ErrorCode error_code;
};

message MsgSvrCli_EquipItem_Ntf		: 0x00002005
{
	int64 item_no;
};

message MsgCliSvr_UnequipItem_Req	: 0x00002006
{
	EquipItemPartType part_type;
};

message MsgSvrCli_UnequipItem_Ans	: 0x00002006
{
	ErrorCode error_code;
};

message MsgSvrCli_UnequipItem_Ntf	: 0x00002007
{
	EquipItemPartType part_type;
};

message MsgCliSvr_SellItem_Req		: 0x00002008
{
	int64	item_no;
	int32	item_count;
};

message MsgSvrCli_SellItem_Ans		: 0x00002008
{
	ErrorCode error_code;
};


.cpp %%
}}
%%
.cs %%
}}
%%