.cpp %%
#include "data.h"
%%

.cs %%
using data;
%%

message MsgCliSvr_Login_Req	:		00000001
{
	string user_id;
};

message MsgSvrCli_Login_Ans :		00000001
{
	ErrorCode error_code;
	UserData user_data;
};

message MsgCliSvr_JoinChannel_Req : 00010001
{
};

message MsgSvrCli_JoinChannel_Ans : 00010001
{
	ErrorCode error_code;
};

message MsgSvrCli_JoinChannel_Ntf : 10010001
{
	string session_key;
	int32 session_count;
};

message MsgCliSvr_SendMessage_Ntf : 00010002
{
	int64 msg_seq;
};

message MsgSvrCli_SendMessage_Ntf : 10010002
{
	int64 msg_seq;
};

message MsgCliSvr_LeaveChannel_Req : 00010003
{
};

message MsgSvrCli_LeaveChannel_Ans : 00010003
{
	ErrorCode error_code;
};

message MsgSvrCli_LeaveChannel_Ntf : 10010003
{
	string session_key;
};


message MsgSvrCli_Kickout_Ntf 	: 10000003
{
	ErrorCode error_code;
};

message MsgCliSvr_HeartBeat_Ntf	: 10000004
{
	uint32 msg_seq;
};

message MsgSvrCli_HeartBeat_Ntf : 10000004
{
	uint32 msg_seq;
};
