.cpp %%
#include <sstream>
#include <memory>
namespace Gamnet { namespace Network { namespace Router {
%%

message MsgRouter_Connect_Req				: 001
{
	string	service_name;
	uint32	id;
};

message MsgRouter_Connect_Ans				: 002
{
	int32	error_code;
	string	service_name;
	uint32	id;
};

message MsgRouter_RegisterAddress_Req		: 003
{
	string	service_name;
	uint32	id;
	int32	router_port;
};

message MsgRouter_RegisterAddress_Ans		: 004
{
	int32	error_code;
	string	service_name;
	uint32	id;
	int32	router_port;
};

message MsgRouter_RegisterAddress_Ntf		: 005
{
	string	service_name;
	uint32	id;
};

message MsgRouter_SendMsg_Ntf				: 006
{
	uint32 msg_seq;
	string buffer;
};

message MsgRouter_HeartBeat_Ntf				: 007
{
};

.cpp %%
}}}
%%
