enum ErrorCode {
	Success = 0,
	MessageFormatError = 1000,
	MessageSeqOmmitError = 1001,
	InvalidUserError = 2000,
	InvalidAccessTokenError = 2001,
	DuplicateConnectionError = 3000,
	ReconnectTimeoutError = 4000,
	ResponseTimeoutError = 4001,
	AlreadyLoginSessionError = 5000,
	CanNotCreateCastGroup = 5001
};

struct ChatUserData 
{
	string UserID;
	string PersonalData;
};


message MsgCliSvr_Login_Req : 00000010
{
	string UserID;
};

message MsgSvrCli_Login_Ans : 00000010
{
	ErrorCode Error;
	ChatUserData UserData;
};

message MsgCliSvr_JoinChannel_Req : 00010001
{
};

message MsgSvrCli_JoinChannel_Ans : 00010001
{
	ErrorCode Error;
	int64 ChannelSEQ;
	list<ChatUserData> ExistingUserData;
};

message MsgSvrCli_JoinChannel_Ntf : 10010001
{
	ChatUserData NewUserData;
};

message MsgCliSvr_SendMessage_Ntf : 00010002
{
	int64 ChatSEQ;
	string ChatMessage;
};

message MsgSvrCli_SendMessage_Ntf : 10010002
{
	int64 ChatSEQ;
	string ChatMessage;
};

message MsgCliSvr_LeaveChannel_Req : 00010003
{
};

message MsgSvrCli_LeaveChannel_Ans : 00010003
{
	ErrorCode Error;
};

message MsgSvrCli_LeaveChannel_Ntf : 10010003
{
	ChatUserData LeaveUserData;
};

message MsgSvrCli_Kickout_Ntf : 10000003
{
	ErrorCode Error;
};