.cpp %%
namespace Gamnet {
%%

.cs %%
//
//
//
%%

message MsgNetwork_Connect_Req 		: 0001
{
	string user_id;
};

message MsgNetwork_Connect_Ans 		: 0001
{
	uint32 error_code;
	uint64 session_key;
	string session_token;
};

message MsgNetwork_Reconnect_Req	: 0002
{
	uint64 session_key;
	string session_token;
};

message MsgNetwork_Reconnect_Ans	: 0002
{
	uint32 error_code;
	uint64 session_key;
	string session_token;
	uint32 msg_seq;
};

message MsgNetwork_Kickout_Ntf 		: 0003
{
	uint32 error_code;
};

message MsgNetwork_HeartBeat_Req	: 0004
{
};

message MsgNetwork_HeartBeat_Ans 	: 0004
{
};

.cpp 
%%
}
%%